#! /usr/bin/env bash

#
# img-chroot – script for execute commands in file-image, copy files
# Copyright 2018-2020 Artem Smirnov @urpylka
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e # Exit immidiately on non-zero result

echo_stamp() {
  # TEMPLATE: echo_stamp <TEXT> <TYPE> <BOOL_CARRIER>
  # TYPE: SUCCESS, ERROR, INFO

  # More info there https://www.shellhacks.com/ru/bash-colors/

  TEXT="$(date '+[%Y-%m-%d %H:%M:%S]') $1"
  TEXT="\e[1m$TEXT\e[0m" # BOLD

  case "$2" in
    SUCCESS)
    TEXT="\e[32m${TEXT}\e[0m";; # GREEN
    ERROR)
    TEXT="\a\e[31m${TEXT}\e[0m"; # RED
    TEXT="\a${TEXT}";; # SOUND
    INFO)
    TEXT="\e[34m${TEXT}\e[0m";; # BLUE
  esac

  if [ ! -z $3 ]; then
    echo -ne ${TEXT}
  else
    echo -e ${TEXT}
  fi
}

# This script doesn't work on Ubuntu because OS`s losetup does not consist --partscan (-P).

# Idea: use `mount -o loop,offset`
# https://stefanoprenna.com/blog/2014/09/22/tutorial-how-to-mount-raw-images-img-images-on-linux/
# REPO_DIR=$(mktemp -d --suffix=.builder_repo)
# mount -t ext4 -o loop,offset=$((94208 * 512)) image/clever_qemu_test_2_20180822_163141.img "$REPO_DIR"
# mount -t vfat -o loop,offset=$((8192 * 512)) image/clever_qemu_test_2_20180822_163141.img "$REPO_DIR/boot"

execute() {
  # execute <IMAGE_PATH> [<EXECUTE_FILE> [...]]

  echo_stamp "Mount loop-image: $1"
  local DEV_IMAGE=$(losetup -f) && losetup -Pf $1
  sleep 0.5

  RET=0

  # TODO: Check if it is Raspbian image w 2 partitions
  #       or if it have one partition

  local MOUNT_POINT=$(mktemp -d --suffix=.builder_image)
  echo_stamp "Mount dirs ${MOUNT_POINT} & ${MOUNT_POINT}/boot" "INFO"
  mount "${DEV_IMAGE}p2" ${MOUNT_POINT}
  mount "${DEV_IMAGE}p1" ${MOUNT_POINT}/boot

  echo_stamp "Bind system dirs"

  echo_stamp "Mounting /proc in chroot... " "INFO" 1
  if [ ! -d ${MOUNT_POINT}/proc ]; then
    mkdir -p ${MOUNT_POINT}/proc; fi
  mount -t proc -o nosuid,noexec,nodev proc ${MOUNT_POINT}/proc \
  && echo_stamp "OK" "SUCCESS" \
  || (echo_stamp "Failed" "ERROR"; exit 1)

  echo_stamp "Mounting /sys in chroot... " "INFO" 1
  if [ ! -d ${MOUNT_POINT}/sys ]; then
    mkdir -p ${MOUNT_POINT}/sys; fi
  mount -t sysfs -o nosuid,noexec,nodev sysfs ${MOUNT_POINT}/sys \
  && echo_stamp "OK" "SUCCESS" \
  || (echo_stamp "Failed" "ERROR"; exit 1)

  echo_stamp "Mounting /dev/ and /dev/pts in chroot... " "INFO" 1 \
  && mkdir -p -m 755 ${MOUNT_POINT}/dev/pts \
  && mount -t devtmpfs -o mode=0755,nosuid devtmpfs ${MOUNT_POINT}/dev \
  && mount -t devpts -o gid=5,mode=620 devpts ${MOUNT_POINT}/dev/pts \
  && echo_stamp "OK" "SUCCESS" \
  || (echo_stamp "Failed" "ERROR"; exit 1)

  echo_stamp "Copy DNS records "  "INFO" 1 \
  && cp -L /etc/resolv.conf ${MOUNT_POINT}/etc/resolv.conf \
  && echo_stamp "OK" "SUCCESS" \
  || (echo_stamp "Failed" "ERROR"; exit 1)

  set +e
  mv ${MOUNT_POINT}/etc/ld.so.preload ${MOUNT_POINT}/etc/ld.so.preload.temp-moved

  if [[ $# > 1 ]]; then
    echo_stamp "Copying script to chroot fs" "INFO"

    local SCRIPT_NAME="$(basename $2).$(tr -dc 'A-F0-9' < /dev/urandom | dd bs=1 count=7 2>/dev/null)"
    local SCRIPT_DIR="${MOUNT_POINT}/root"

    cp "$2" "${SCRIPT_DIR}/${SCRIPT_NAME}"
    # Run script in chroot with additional arguments
    chroot ${MOUNT_POINT} /bin/sh -c "/root/${SCRIPT_NAME} ${@:3}" || RET=1
    # Removing script from chroot fs
    rm "${SCRIPT_DIR}/${SCRIPT_NAME}"
  else
    # https://wiki.archlinux.org/index.php/Change_root_(%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9)
    # http://www.unix-lab.org/posts/chroot/
    # https://habrahabr.ru/post/141012/
    # https://losst.ru/vosstanovlenie-grub2
    # http://unixteam.ru/content/virtualizaciya-ili-zapuskaem-prilozhenie-v-chroot-okruzhenii-razmyshleniya
    # http://help.ubuntu.ru/wiki/%D0%B2%D0%BE%D1%81%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_grub
    echo_stamp "Entering chroot" "INFO" \
    && chroot ${MOUNT_POINT} /bin/bash
  fi

  mv ${MOUNT_POINT}/etc/ld.so.preload.temp-moved ${MOUNT_POINT}/etc/ld.so.preload
  umount_system ${MOUNT_POINT} ${DEV_IMAGE}
  set -e
  exit ${RET}
}

# https://gist.github.com/letmaik/caa0f6cc4375cbfcc1ff26bd4530c2a3
# https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/templates/header.sh
my_travis_retry() {
  local result=0
  local count=1
  while [ $count -le 3 ]; do
    [ $result -ne 0 ] && {
      echo -e "\n${ANSI_RED}The command \"$@\" failed. Retrying, $count of 3.${ANSI_RESET}\n" >&2
    }
    # ! { } ignores set -e, see https://stackoverflow.com/a/4073372
    ! { "$@"; result=$?; }
    [ $result -eq 0 ] && break
    count=$(($count + 1))
    sleep 1
  done

  [ $count -gt 3 ] && {
    echo -e "\n${ANSI_RED}The command \"$@\" failed 3 times.${ANSI_RESET}\n" >&2
  }

  return $result
}

umount_system() {
  # TEMPLATE: umount_system <MOUNT_POINT> <DEV_IMAGE>

  echo_stamp "Unmount chroot rootfs and boot partition: $1"
  my_travis_retry umount -fl $1
  losetup -d $2
}

copy_to_image() {
  # copy_to_image <IMAGE_PATH> <MOVE_FILE> <MOVE_TO>

  echo_stamp "Mount loop-image: $1"
  local DEV_IMAGE=$(losetup -f) && losetup -Pf $1
  sleep 0.5

  local MOUNT_POINT=$(mktemp -d --suffix=.builder_image)
  echo_stamp "Mount dirs ${MOUNT_POINT} & ${MOUNT_POINT}/boot"
  mount "${DEV_IMAGE}p2" ${MOUNT_POINT}
  mount "${DEV_IMAGE}p1" ${MOUNT_POINT}/boot

  local dir_name=$(dirname "${MOUNT_POINT}$3 /")

  [[ ! -d ${dir_name} ]] && mkdir -p ${dir_name} \
  && echo_stamp "Created ${dir_name}" "SUCCESS"

  cp -r "$2" "${MOUNT_POINT}$3"
  umount_system ${MOUNT_POINT} ${DEV_IMAGE}
}

if [ $(whoami) != "root" ]; then
  echo ""
  echo "********************************************************************"
  echo "******************** This should be run as root ********************"
  echo "********************************************************************"
  echo ""
  exit 1
fi

echo "================================================================================"
for ((i=0; i<=$#; i++)); do echo "\$$i: ${!i}"; done
echo "================================================================================"

if [[ $# > 0 ]]; then
  [[ -f $1 ]] || (echo_stamp "$1 does not exist" "ERROR"; echo "Template: img-chroot <IMAGE> [ exec <SCRIPT> [...] | copy <MOVE_FILE> <MOVE_TO> ]"; exit 1)

  if [[ ! -z $2 ]]; then
    case "$2" in
      exec)
        execute $1 $3 ${@:4};;
      copy)
        copy_to_image $1 $3 $4;;
      *)
        echo "Template: img-chroot <IMAGE> [ exec <SCRIPT> [...] | copy <MOVE_FILE> <MOVE_TO> ]";;
    esac
  else execute $1; fi
fi
